{% set version = "2019.10-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bb
  version: {{ version|replace("-", "_") }}

source:
  fn: BB_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/BB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BB/BB_{{ version }}.tar.gz
  sha256: 04d0b6ce6e5f070b109478a6005653dbe78613bb4e3ea4903203d851b5d3c94d

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-quadprog
  run:
    - r-base
    - r-quadprog

test:
  commands:
    - $R -e "library('BB')"           # [not win]
    - "\"%R%\" -e \"library('BB')\""  # [win]

about:
  home: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
  license: GPL-3
  summary: Barzilai-Borwein spectral methods for solving nonlinear system of equations, and for
    optimizing nonlinear objective functions subject to simple constraints. A tutorial
    style introduction to this package is available in a vignette on the CRAN download
    page or, when the package is loaded in an R session, with vignette("BB").
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
