travis:
  secure:
    BINSTAR_TOKEN: tMVkKu56ZYf6FioZdYCd3FWzF/6U6evh0G5TAipjiZzl9hknyW4EGOVbCB980zWize2GNQNwhql2KVKe/P+OHKc/5tGb5VPGKsmnpLN+8Gt06T5I4o8r1jsSQN857JqtaaYRWtlAcXw+vsGORCOtittVNvJS+n+0Syc9e8np00DFG/iV1NVrC+vAvyuJmEH0MeSqWv31cnk4r6Vx0q2utixa0juXcmKDxwUJ6iQJ11/2Zdd/DpEzAMaSmKIzBPOb/rimvtSsrD9DCV8arx7GnwWI9ypdDKXcLyO4v3Mhu5njhBQn3FH3DtS+O+uhTVhP9HSpmtGPystepctBJxF7EvR45XMBWGaHepeGwUT8KXWAd8e1c4TnBoFi4Zcfshvmqw/OqvUXtGr+BBiKQuQjvtJgmXM6d7OryVp4XXjJli4RnMRBPkqwtQlTQi5JDI2geVhfw0ekCXuIGFnsbspdy9LBnxF6fnPUcNsFe3xfA7y0/4iTtNonCX4N1mR0ncVRj669xagOBYjMDAuYEBnM3HIhXQC8HkmBSmOBvY9YcjH/r8DzdW4zCGT+A6sIEBlTXoThlA+p3nzoaFo8N2f5CUQqOwKTbETympfVxtOyFanfMf37cvK3XQ6kZ+QMuT8eFlQs2eI/PJK4Xr0jb4vXBkscpSnZg1lfQDN61dQzD00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
