travis:
  secure:
    BINSTAR_TOKEN: CFndQMu42uzaEpcrPGXyx5iqQVmkP7UwwKZ2XEG2bCIFCyjdNoZZvUxjFT81eHWJhT2XwHTJlOzlCG8e/cAx+t5hLGUtMI21AGSBZOA6BEdjyQHjytf+t6LnQPt99uJV8pnv0YijwP2Ur//EAERM8a9CfUSPZTEaFLj1GX5FFYVixi2CkxzY73Q4PjssTf2h+OeVJ8TDt1YFnm2DBSn3I/O0UBB5ZNnZjG5cUh1E/dYmr+BPAxusNgcld6FmUYBqRd6qH3UHt3TBIjTVDUwDEUfLRz0RDVSKnrNFDCgs3ahyZVnSr8ZymlkoSqZV+a/MGfDLgJ7ROkr2/S0fto7MmNaFydrvNFaZPC1JM+x2D/gGvXbwUriQN0DnYVChbwWC0nKkUFGjWkp6cOx9j8DSSLcvQgRMiyrkF3tIEPW6SAJzoW3euQqrDzsKRrzahOJEclSpd9t3RvvyJnsLlbIXWo2wcdFD2QjyLQyvvr/oQpes0Kv+4NcRvdo6IAJIWPyVufulp7w3thrjxCO7wlW55msebwukyX0Ay7WkC8XZlGIBwWEzvjcjJlErOoptShNUkMWDMsSU8SYSydpoVxaQgl2y+bQwHelBGPjWzk9v9oNe3+Ok1skXSUIEcNpQm5BhrPatUGgN/x65brtGFSdEH4TWhZnwU3BvBC8SFcndJ1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
