travis:
  secure:
    BINSTAR_TOKEN: yJ1dQdxu2Gq4V00Qwt4jlpaHpj1V9Bj3jLSSX/QgkcZMujnL+47/U5hCdbbsYAboaLCXuwNEVjzciRxhtfr9+lamzL4reE46ErlsL39EB/fMM1krMZbLlx7Zhbu8hTIbJcuBzw26g6Bjvpt79otCh/L7EX2k9NMo25ODysbGxt3rW6DiOtt6MSb/C+O61JC4kYjE3KxKOhXq1vOvnf3Fek9zu2kNsfnxtmbRkaixdw9ZffJvyRcx8mGIVJXotTxFRK9zX3P2jE0gqchC9UOz/2kfOeQx/BmKa7MNab/A9Zp6TqIxhZ5qE/PlvPSVBu6fOqdixK50NkmdOPJoE62XL68TJgEq0JxWzJyBqkCpt6ACFN0Lu7fYqxnaI5TiHwUSTSMsRJ35HSOyOODJn9bZ8Tps0HZ/vVIDBs4vPCbs8MlgOrbDtFft9HWWp1BPK50RkkQYGAbu71NLGAIGwBOHAzDlK6SbpBTuCTW+qURlDl1YOv1aCXI9NfgbF+RcAnYKhqMgehMLvUEzdaHfHhgAxfGHvYG8fhDqxCPK0E7evkaT6x7FbbRnfAf65a2faCAfg5kLvfpkgqdpUXDUhmQ671Y41iiOL1AfTQMkF5/Lb+OjJrpk1dc1Qeyp/BJNIrJCjMU1wzmm8qJ6G6332xFd9dFnTXnVOAeYd7D5njahV3c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
