travis:
  secure:
    BINSTAR_TOKEN: KsIKv237TYAF2qgWFJFB99ItbpmOwLNUKEC/kr4cMwVBVtHLo36ZfWhKBSE/0t88CXAlIKtyJYzcJwHBYFHhno37RMa5rK8IhNPlpFAdvnpcLociwZHdG9YspfpQgNBzZKhztrL2HLxKgBarFcDELqABungJzrKYbIUVFeM8XQh8mvte9NIIpMjgt15stXINxy647MBFCwmaeb2hfQ1BUwGPeWNPzqrlKxG+50KOwwE4vFopnxQoFsprwnJLUn0C0w1tVlFfp7IvqFKcZLCgvJzxZLYRilitBQioMi1l2sMyi3Zpe5MMHH5KTpEAJlJ9Vov4bZ6xc6TCSO+Adj/7oDgA7zYx8I5UfHQDASQ3TIPhVQoKCVNfHuLJP3Kv4nCEkmUFl8cdK40/okqgG5Xuopx7rDTO7ZbruJIt6yljPBgck6vHBOoK3UOlbIy43+/V3Y96P8neo71rpXVH78x1VCYPlqXIJJ53IuaNcMjrpUDmA8Y9uoJCbRfZbqQOJ7fDNmKF2KjQieGTizIvzLPZ9zdMNEqafBSKq46ZqPA/inxq1AVsD2vVakWQ3BbJrzYlttz3rHSuNuzHQFbsPWKjj0jnC4JSFDIkgEXefQyMd5esx3ntWjq0jW9S2VZb5T0zHSaCIqeDf1g79ICFmokmKB3RBnUcxdgH1/f+eMBmPEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
